# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create

require "rubocop/rake_task"
require "tmpdir"

RuboCop::RakeTask.new do |task|
  task.options = ["--cache-root", File.join(File.realpath(Dir.tmpdir), "anydoc-rubocop-cache")]
end

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("anydoc.gemspec")

RbSys::ExtensionTask.new("anydoc", GEMSPEC) do |ext|
  ext.lib_dir = "lib/anydoc"
end

task default: %i[compile test rubocop]
