[package]
name = "anydoc"
version = "0.1.3-ruby.0"
edition = "2024"
authors = ["Nick Pezza <pezza@hey.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anydoc-core = { package = "anydoc", version = "=0.1.3" }
magnus = "0.8.2"
rb-sys = { version = "0.9", features = ["stable-api-compiled-fallback"] }

[build-dependencies]
rb-sys-env = "0.2.2"

[dev-dependencies]
rb-sys-test-helpers = { version = "0.2.2" }
